---
abstract: 'Silly Bot::Cobalt plugins'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Cobalt-Plugin-Silly
provides:
  Bot::Cobalt::Plugin::Silly:
    file: lib/Bot/Cobalt/Plugin/Silly.pm
    version: 0.02
  Bot::Cobalt::Plugin::Silly::AutoOpAll:
    file: lib/Bot/Cobalt/Plugin/Silly/AutoOpAll.pm
    version: 0
  Bot::Cobalt::Plugin::Silly::BoneEasy:
    file: lib/Bot/Cobalt/Plugin/Silly/BoneEasy.pm
    version: 0
  Bot::Cobalt::Plugin::Silly::DailyFail:
    file: lib/Bot/Cobalt/Plugin/Silly/DailyFail.pm
    version: 0
  Bot::Cobalt::Plugin::Silly::LOLCAT:
    file: lib/Bot/Cobalt/Plugin/Silly/LOLCAT.pm
    version: 0
  Bot::Cobalt::Plugin::Silly::OutputLOLCAT:
    file: lib/Bot/Cobalt/Plugin/Silly/OutputLOLCAT.pm
    version: 0
  Bot::Cobalt::Plugin::Silly::OutputLeet:
    file: lib/Bot/Cobalt/Plugin/Silly/OutputLeet.pm
    version: 0
  Bot::Cobalt::Plugin::Silly::Reverse:
    file: lib/Bot/Cobalt/Plugin/Silly/Reverse.pm
    version: 0
  Bot::Cobalt::Plugin::Silly::Rot13:
    file: lib/Bot/Cobalt/Plugin/Silly/Rot13.pm
    version: 0
requires:
  Acme::Daily::Fail: 0
  Acme::LeetSpeak: 0
  Bone::Easy: 0
  Bot::Cobalt::Common: 0
  Bot::Cobalt::Core: 0
  Bot::Cobalt::Serializer: 0
  Object::Pluggable::Constants: 0
  POE::Filter::LOLCAT: 0
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  XML::Simple: 0
  perl: v5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
